### ISSUE TITLE
static dir conflict #Urgent

### ISSUE THREAD

**Issue by ujjwalnp** [cosmicgz/COREQ#40]
Error message :
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Feed`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Feed`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:125387:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:125408:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:114499:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:114549:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:117491:32)
    at updateHostComponent (http://localhost:3000/static/js/bundle.js:118135:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:119580:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:104566:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:104610:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:104667:35)

**Comment by Hunter-420** [comment]
solved successfully
